/// Authorized inspection type for the current inspector.
/// GET /api/mobile/visits/inspection-types?inspectorId=...
class InspectionType {
  final int id;
  final String name;
  final String? nameAr;
  final String? icon;

  const InspectionType({required this.id, required this.name, this.nameAr, this.icon});

  factory InspectionType.fromJson(Map<String, dynamic> j) {
    final code = (j['inspectionCode'] ?? j['code']) as String?;
    return InspectionType(
      id: ((j['id'] ?? j['inspectionTypeId'] ?? 0) as num).toInt(),
      name: (j['name'] ?? j['inspectionName'] ?? '').toString(),
      nameAr: (j['nameAr'] as String?) ?? _arabicByCode(code),
      icon: (j['icon'] ?? code) as String?,
    );
  }

  static String? _arabicByCode(String? code) {
    switch (code) {
      case 'HOUSING':
        return 'الرقابة على السكن الجماعي';
      case 'MARKET':
        return 'الرقابة على الأسواق';
      case 'HEALTH':
        return 'الرقابة الصحية';
      default:
        return null;
    }
  }
}

/// Response from POST /api/mobile/visits/verify-license.
///
/// The backend returns HTTP 200 even when the licence isn't found — callers
/// must check [found] (not just catch HTTP errors) to detect an invalid
/// licence number.
class LicenseVerificationResponse {
  /// true only when the licence number exists in the registry.
  final bool found;
  final int? licenseId;
  final String licenseNumber;
  final int? establishmentId;
  final String? establishmentName;
  final String? establishmentNameAr;
  final String? licenseType;
  final String? licenseStatus;
  final String? mobileNumber;
  final String? city;
  final double? latitude;
  final double? longitude;

  /// Server-supplied message — used as the error text when [found] is false.
  final String? message;

  const LicenseVerificationResponse({
    this.found = false,
    this.licenseId,
    required this.licenseNumber,
    this.establishmentId,
    this.establishmentName,
    this.establishmentNameAr,
    this.licenseType,
    this.licenseStatus,
    this.mobileNumber,
    this.city,
    this.latitude,
    this.longitude,
    this.message,
  });

  factory LicenseVerificationResponse.fromJson(Map<String, dynamic> j) => LicenseVerificationResponse(
        // Prefer the explicit flag; fall back to "a licenseId came back".
        found: (j['found'] as bool?) ?? (j['licenseId'] != null),
        licenseId: j['licenseId'] as int?,
        licenseNumber: (j['licenseNumber'] ?? '').toString(),
        establishmentId: j['establishmentId'] as int?,
        establishmentName: j['establishmentName'] as String?,
        establishmentNameAr: (j['establishmentNameAr'] ?? j['establishmentNameArabic']) as String?,
        licenseType: j['licenseType'] as String?,
        licenseStatus: j['licenseStatus'] as String?,
        mobileNumber: (j['mobileNumber'] ?? j['mobile']) as String?,
        city: j['city'] as String?,
        latitude: (j['latitude'] as num?)?.toDouble(),
        longitude: (j['longitude'] as num?)?.toDouble(),
        message: j['message'] as String?,
      );
}

/// Response from POST /api/mobile/visits → returns inspectionId and the
/// BPMN process-tracking fields generated by the backend.
class CreateVisitResponse {
  final int inspectionId;
  final String? inspectionNumber;
  final String? status;

  /// Backend-generated business key (e.g. INS-20260521-00042) — shown in the
  /// UI as the case ID and used by Camunda/Operate to correlate the process.
  final String? businessKey;

  /// Zeebe process instance key — non-null only when the BPMN process started.
  final int? processInstanceKey;

  /// STARTED / NOT_STARTED / FAILED — state of the PerformInspection process.
  final String? processStatus;

  const CreateVisitResponse({
    required this.inspectionId,
    this.inspectionNumber,
    this.status,
    this.businessKey,
    this.processInstanceKey,
    this.processStatus,
  });

  factory CreateVisitResponse.fromJson(Map<String, dynamic> j) => CreateVisitResponse(
        inspectionId: (j['inspectionId'] ?? j['id'] ?? 0) as int,
        inspectionNumber: j['inspectionNumber'] as String?,
        status: j['status'] as String?,
        businessKey: j['businessKey'] as String?,
        processInstanceKey: (j['processInstanceKey'] as num?)?.toInt(),
        processStatus: j['processStatus'] as String?,
      );
}

/// Body for POST /api/mobile/visits and /no-license.
class VisitCreateRequest {
  final String inspectionNumber;
  final int inspectionTypeId;
  final int? establishmentId;
  final int? licenseId;
  final bool licenseAvailable;
  final String licenseEntryMethod;
  final String inspectionMode;
  final DateTime inspectionDate;
  final double? latitude;
  final double? longitude;
  final bool familyRelationshipDisclosed;
  final FacilityCreateRequest? facility;

  const VisitCreateRequest({
    required this.inspectionNumber,
    required this.inspectionTypeId,
    this.establishmentId,
    this.licenseId,
    this.licenseAvailable = true,
    this.licenseEntryMethod = 'LICENSE_NUMBER',
    this.inspectionMode = 'ON_SITE',
    required this.inspectionDate,
    this.latitude,
    this.longitude,
    this.familyRelationshipDisclosed = false,
    this.facility,
  });

  Map<String, dynamic> toJson() => {
        'inspectionNumber': inspectionNumber,
        'inspectionTypeId': inspectionTypeId,
        if (establishmentId != null) 'establishmentId': establishmentId,
        if (licenseId != null) 'licenseId': licenseId,
        'licenseAvailable': licenseAvailable,
        'licenseEntryMethod': licenseEntryMethod,
        'inspectionMode': inspectionMode,
        'inspectionDate': inspectionDate.toIso8601String(),
        if (latitude != null) 'latitude': latitude,
        if (longitude != null) 'longitude': longitude,
        'familyRelationshipDisclosed': familyRelationshipDisclosed,
        if (facility != null) 'facility': facility!.toJson(),
      };
}

class FacilityCreateRequest {
  final String facilityName;
  final String? facilityNameAr;
  final String location;
  final String city;
  final double latitude;
  final double longitude;
  final int isicId;
  final int isicDetailId;

  const FacilityCreateRequest({
    required this.facilityName,
    this.facilityNameAr,
    required this.location,
    required this.city,
    required this.latitude,
    required this.longitude,
    required this.isicId,
    required this.isicDetailId,
  });

  Map<String, dynamic> toJson() => {
        'facilityName': facilityName,
        if (facilityNameAr != null) 'facilityNameAr': facilityNameAr,
        'location': location,
        'city': city,
        'latitude': latitude,
        'longitude': longitude,
        'isicId': isicId,
        'isicDetailId': isicDetailId,
      };
}
